default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: alexandria_development

test:
  <<: *default
  database: alexandria_test

production:
  <<: *default
  database: alexandria_production